const DummyData = [
    {
        "root": {
            "id": "toplevel",
            "relevance": 1.0,
            "fields": {
                "totalCount": 162
            },
            "coverage": {
                "coverage": 100,
                "documents": 5363,
                "full": true,
                "nodes": 1,
                "results": 1,
                "resultsFull": 1
            },
            "children": [
                {
                    "id": "id:bqcompany2:bqcompany2::330098815",
                    "relevance": 8.206787861139798,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::330098815",
                        "bq_company_name": "HYUNDAI MOTOR AMERICA",
                        "bq_year_founded": "1985",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "New Car Dealers",
                        "bq_company_ein": "330098815",
                        "bq_naics_code": "441110",
                        "bq_organization_jurisdiction_code": "US_CA",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 1026415387.0,
                        "bq_company_address1_line_1": "10550 Talbert Ave",
                        "bq_company_address1_city": "Fountain Valley",
                        "bq_company_address1_state": "CA",
                        "bq_company_address1_state_name": "California",
                        "bq_company_address1_county_fips": "06059",
                        "bq_company_address1_county_name": "Orange County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "92708",
                        "bq_company_address1_zip9": "92708-6031",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "31080",
                        "bq_company_address1_cbsa_name": "Los Angeles-Long Beach-Anaheim, CA",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 33.70165,
                            "lng": -117.94501
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::953141669",
                    "relevance": 7.84760076366169,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::953141669",
                        "bq_company_name": "TOYOTA MOTOR CORP",
                        "bq_industry_name": "Motor Vehicle Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Single-entity organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "Automobile Manufacturing; Light Truck and Utility Vehicle Manufacturing; Heavy Duty Truck Manufacturing",
                        "bq_company_ein": "953141669",
                        "bq_naics_code": "336111; 336112; 336120",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 266690397301.0,
                        "bq_company_address1_line_1": "6565 Headquarters Dr",
                        "bq_company_address1_city": "Plano",
                        "bq_company_address1_state": "TX",
                        "bq_company_address1_state_name": "Texas",
                        "bq_company_address1_county_fips": "48085",
                        "bq_company_address1_county_name": "Collin County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "75024",
                        "bq_company_address1_zip9": "75024-5965",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "19100",
                        "bq_company_address1_cbsa_name": "Dallas-Fort Worth-Arlington, TX",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 33.08024,
                            "lng": -96.84543
                        },
                        "bq_public_indicator": "true",
                        "bq_revenue_growth_yoy_mr": "0.003309349550949525"
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::380549190",
                    "relevance": 7.84760076366169,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::380549190",
                        "bq_company_name": "FORD MOTOR CO",
                        "bq_year_founded": "1997",
                        "bq_industry_name": "Motor Vehicle Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "New Car Dealers",
                        "bq_company_ein": "380549190",
                        "bq_naics_code": "441110",
                        "bq_organization_jurisdiction_code": "US_MI",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 158057000000.0,
                        "bq_company_address1_line_1": "Tax Department 1 American Road Ford Whq Room 612",
                        "bq_company_address1_city": "Dearborn",
                        "bq_company_address1_state": "MI",
                        "bq_company_address1_state_name": "Michigan",
                        "bq_company_address1_county_fips": "26163",
                        "bq_company_address1_county_name": "Wayne County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "48126",
                        "bq_company_address1_zip9": "48126",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "No Match",
                        "bq_company_address1_rdi": "Unknown",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "19820",
                        "bq_company_address1_cbsa_name": "Detroit-Warren-Dearborn, MI",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 42.33212,
                            "lng": -83.18309
                        },
                        "bq_public_indicator": "true"
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::270383222",
                    "relevance": 7.84760076366169,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::270383222",
                        "bq_company_name": "GENERAL MOTORS CO",
                        "bq_industry_name": "Motor Vehicle Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Single-entity organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "Automobile Manufacturing; Light Truck and Utility Vehicle Manufacturing; Heavy Duty Truck Manufacturing",
                        "bq_company_ein": "270383222",
                        "bq_naics_code": "336111; 336112; 336120",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 156735000000.0,
                        "bq_company_address1_line_1": "300 Renaissance Ctr",
                        "bq_company_address1_city": "Detroit",
                        "bq_company_address1_state": "MI",
                        "bq_company_address1_state_name": "Michigan",
                        "bq_company_address1_county_fips": "26163",
                        "bq_company_address1_county_name": "Wayne County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "48243",
                        "bq_company_address1_zip9": "48243-1402",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "Yes",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_location": {
                            "lat": 42.32997,
                            "lng": -83.03991
                        },
                        "bq_public_indicator": "true"
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::952041006",
                    "relevance": 7.431969081853248,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::952041006",
                        "bq_company_name": "HONDA MOTOR CO LTD",
                        "bq_industry_name": "Motor Vehicle Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Single-entity organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "Automobile Manufacturing; Light Truck and Utility Vehicle Manufacturing; Heavy Duty Truck Manufacturing",
                        "bq_company_ein": "952041006",
                        "bq_naics_code": "336111; 336112; 336120",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 122932331334.0,
                        "bq_company_address1_line_1": "1919 Torrance Blvd",
                        "bq_company_address1_city": "Torrance",
                        "bq_company_address1_state": "CA",
                        "bq_company_address1_state_name": "California",
                        "bq_company_address1_county_fips": "06037",
                        "bq_company_address1_county_name": "Los Angeles County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "90501",
                        "bq_company_address1_zip9": "90501-2722",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "31080",
                        "bq_company_address1_cbsa_name": "Los Angeles-Long Beach-Anaheim, CA",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 33.83642,
                            "lng": -118.31611
                        },
                        "bq_public_indicator": "true",
                        "bq_revenue_growth_yoy_mr": "0.0024457253381353627"
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::630636444",
                    "relevance": 7.431969081853248,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::630636444",
                        "bq_company_name": "TIFFIN MOTOR HOMES, INC.",
                        "bq_year_founded": "1985",
                        "bq_industry_name": "Motor Vehicle Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "Used Car Dealers",
                        "bq_company_ein": "630636444",
                        "bq_naics_code": "441120",
                        "bq_organization_jurisdiction_code": "US_DE",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 762196795.0,
                        "bq_company_address1_line_1": "PO Box 387",
                        "bq_company_address1_city": "Red Bay",
                        "bq_company_address1_state": "AL",
                        "bq_company_address1_state_name": "Alabama",
                        "bq_company_address1_county_fips": "01059",
                        "bq_company_address1_county_name": "Franklin County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "35582",
                        "bq_company_address1_zip9": "35582-0387",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Residential",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "99999",
                        "bq_company_address1_location": {
                            "lat": 34.4443,
                            "lng": -88.14644
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::221824424",
                    "relevance": 7.188016905761581,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::221824424",
                        "bq_company_name": "KAWASAKI MOTORS CORP., U.S.A.",
                        "bq_year_founded": "1967",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "Used Car Dealers",
                        "bq_company_ein": "221824424",
                        "bq_naics_code": "441120",
                        "bq_organization_jurisdiction_code": "US_DE",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 1106412706.0,
                        "bq_company_address1_line_1": "26972 Burbank",
                        "bq_company_address1_city": "Foothill Ranch",
                        "bq_company_address1_state": "CA",
                        "bq_company_address1_state_name": "California",
                        "bq_company_address1_county_fips": "06059",
                        "bq_company_address1_county_name": "Orange County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "92610",
                        "bq_company_address1_zip9": "92610-2506",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "31080",
                        "bq_company_address1_cbsa_name": "Los Angeles-Long Beach-Anaheim, CA",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 33.67881,
                            "lng": -117.66001
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::371426698",
                    "relevance": 7.100035172950144,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::371426698",
                        "bq_company_name": "HYUNDAI MOTOR MANUFACTURING ALABAMA, LLC.",
                        "bq_year_founded": "2002",
                        "bq_industry_name": "Motor Vehicle Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "New Car Dealers",
                        "bq_company_ein": "371426698",
                        "bq_naics_code": "441110",
                        "bq_organization_jurisdiction_code": "US_DE",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Limited Liability Company",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 1918582289.0,
                        "bq_company_address1_line_1": "700 Hyundai Blvd",
                        "bq_company_address1_city": "Montgomery",
                        "bq_company_address1_state": "AL",
                        "bq_company_address1_state_name": "Alabama",
                        "bq_company_address1_county_fips": "01101",
                        "bq_company_address1_county_name": "Montgomery County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "36105",
                        "bq_company_address1_zip9": "36105-9622",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "33860",
                        "bq_company_address1_cbsa_name": "Montgomery, AL",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 32.27773,
                            "lng": -86.32986
                        }
                    }
                },
              
        
            ]
            }
        }
]

export default DummyData;