export const DummyData=[{
    Company:"Amazon angles",
    Status:" active",
   growth :"8.9%",
    revenue:"$658.774n",
    Headcount:"1M",
},

{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},


{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},
{
    Company:"qss technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
},{
Company: "technosoft",
    Status:" active",
    growth:"9.7%",
    revenue:"$656.9k",
    Headcount:"4M",
}
]